#!/bin/bash

# Place at /var/lib/webosbrew/init.d/start_magic_mapper
# run chmod +x /var/lib/webosbrew/init.d/start_magic_mapper
# Note the homebrew script that executes this won't work if you add an extension like .sh,
# so be sure to leave off the extension


if [ -f "/usr/bin/python" ]; then
  nohup /usr/bin/python -u /home/root/magic_mapper.py > /tmp/magic_mapper.log 2>&1 &
else
  nohup /usr/bin/python3 -u /home/root/magic_mapper.py > /tmp/magic_mapper.log 2>&1 &
fi
